/**
* Problem 2
*
* Each new term in the Fibonacci sequence is generated by adding the
* previous two terms. By starting with 1 and 2, the first 10 terms
* will be :
*      1, 2, 3, 5, 6, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not
* exceed four million, find the sum of the even valued terms.
*
* Answer: 4613732
*/

#include <iostream>

int main() {
	int sum = 0;

	int fib1 = 1, fib2 = 2, temp;

	while (fib2 <= 4000000) {
		if(fib2 % 2 == 0)
			sum += fib2;

		temp = fib1;
		fib1 = fib2;
		fib2 = fib1 + temp;
	}


	std::cout << sum << std::endl;

	system("PAUSE");
	return 0;
}